config/routes.rb
Taskodozer::Application.routes.draw do

  root :to => "pages#home"
  get "/about" => "pages#about", :as => "about"

  devise_for :users

  resources :projects, :except => [:destroy] do
    resources :discussions
    resources :tasks do
      get 'filter/:filter' => "tasks#index", :on => :collection, :as => "filter"
      match 'notes' => "notes#create", :on => :member, :via => :post
      match 'notes/:note_id/edit' => "notes#edit", :on => :member, :via => :get, :as => "edit_note"
      match 'notes/:note_id/' => "notes#update", :on => :member, :as => "update_note"
    end
    resources :topics do
      match 'comments' => "comments#create", :on => :member, :via => :post
      match 'comments/:comment_id/edit' => "comments#edit", :on => :member, :via => :get, :as => "edit_comment"
      match 'comments/:comment_id/' => "comments#update", :on => :member, :as => "update_comment"
    end
  end
  get "/projects/filter/:filter" => "projects#index", :as => "project_filter"
  match "/projects/:id/archive" => "projects#archive", :as => "project_archive", :via => :post
  match "/projects/:id/reactivate" => "projects#reactivate", :as => "project_reactivate", :via => :post
  match "project/:project_id/discussion/:id/archive" => "discussions#archive", :as => "archive_project_discussion", :via => :post
  match "project/:project_id/discussion/:id/reactivate" => "discussions#reactivate", :as => "reactivate_project_discussion", :via => :post

  match "project/:project_id/discussion/:id/topics/new" => "topics#new", :as => "new_project_discussion_topic", :via => :get

  resources :companies, :except => [:index, :show]

  match "/projects/:project_id/accesses/new" => "accesses#new", :via => :get, :as => "new_access"
  match "/accesses" => "accesses#create", :via => :post, :as => "accesses"
  match "/accesses/:project_id" => "accesses#create_self", :via => :post, :as => "accesses_add_self"
  match "/accesses" => "accesses#index", :via => :get, :as => "accesses"
  match "/projects/:project_id/accesses/:user_id" => "accesses#destroy", :as => "access"

  match "/topic/:topic_id/subscribe" => "subscriptions#create_topic_self", :via => :post, :as => "topic_subscriptions_add_self"
  match "/topic/:topic_id/unsubscribe/:user_id" => "subscriptions#destroy_topic", :as => "topic_subscriptions"

  get "administration/management"
  get "/manage" => "administration#home", :as => "administration_home"
  get "/manage/users" => "administration#users", :as => "administration_users"
  get "/manage/users/:id" => "administration#user_edit", :as => "administration_user_edit"
  get "/manage/companies/:id/add" => "administration#user_new", :as => "administration_user_new"
  match "manage/companies/add" => "administration#user_create", :as => "administration_user_create"
  match "/manage/users/:id" => "administration#user_update", :as => "administration_user_update"
  

end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  belongs_to :project
  has_many :topics

  attr_accessible :project_id, :title, :archived

  default_scope :order => 'title'

  validates_presence_of :title
  validates_presence_of :project_id

end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController

  before_filter :init_project

  def archive
    @discussion = Discussion.find(params[:id])
    @discussion.archived = 1
    @discussion.save
    redirect_to project_discussions_url(@project), :notice => "Successfully archived category."
  end

  def reactivate
    @discussion = Discussion.find(params[:id])
    @discussion.archived = 0
    @discussion.save
    redirect_to project_discussion_url(@project, @discussion), :notice => "Successfully reactivated category."
  end

  def index
    @discussions = Discussion.all
  end

  def show
    @discussion = Discussion.find(params[:id])
  end

  def new
    @discussion = Discussion.new
  end

  def create
    @discussion = Discussion.new(params[:discussion])
    @discussion.project = @project
    if @discussion.save
      redirect_to @project, :notice => "Successfully created discussion."
    else
      render :action => 'new'
    end
  end

  def edit
    @discussion = Discussion.find(params[:id])
  end

  def update
    @discussion = Discussion.find(params[:id])
    if @discussion.update_attributes(params[:discussion])
      redirect_to project_discussion_path(@project, @discussion), :notice  => "Successfully updated discussion."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @discussion = Discussion.find(params[:id])
    if @discussion.project == @project
      @discussion.destroy
      redirect_to project_discussions_path(@project), :notice => "Successfully destroyed discussion."
    else
      redirect_to project_discussions_path(@project), :notice => "Access denied."
    end
  end

  private

  def init_project
    @project = Project.find(params[:project_id])
  end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/views/discussions/_form.html.erb
<%= semantic_form_for @discussion, :url => project_discussions_path(@project) do |f| %>
  <%= f.inputs do %>
    <%= f.input :title, :label => "Discussion title" %>
  <% end %>
  <%= f.buttons do %>
    <%= f.commit_button %>
  <% end %>
<% end %>

app/views/discussions/edit.html.erb
<% title "Edit Discussion" %>

<%= semantic_form_for @discussion, :url => project_discussion_path(@project, @discussion) do |f| %>
  <%= f.inputs do %>
    <%= f.input :title, :label => "Discussion title" %>
  <% end %>
  <%= f.buttons %>
<% end %>

<p>
  <%= link_to "Show", project_discussion_path(@project,@discussion) %> |
  <%= link_to "View All", project_discussions_path(@project) %>
</p>

app/views/discussions/index.html.erb
<% title "Discussions" %>

<% content_for :sidebar do %>
	<ul class="actions">
	<li><%= link_to "New Topic", new_project_topic_path(@project) %></li>
	</ul>
	<h2>Discussions <%= link_to "New category", new_project_discussion_path(@project) %></h2>
	<ul>
	<li><%= link_to_unless_current "All", project_discussions_path(@project) %></li>
	<% @project.discussions.each do |discussion| %>
	<li><%= link_to_unless_current discussion.title, project_discussion_path(@project, discussion) %></li>
	<% end %>
	</ul>
<% end %>

<div class="topics">
<%= render @project.topics %>
</div>

app/views/discussions/new.html.erb
<% title "New Discussion" %>

<%= semantic_form_for @discussion, :url => project_discussions_path(@project) do |f| %>
  <%= f.inputs do %>
    <%= f.input :title, :label => "Discussion title" %>
  <% end %>
  <%= f.buttons %>
<% end %>

<p><%= link_to "Back to List", project_discussions_path(@project) %></p>

app/views/discussions/show.html.erb
<% title "#{@project.name}'s discussions: category #{@discussion.title}" %>

<% content_for :sidebar do %>
  <ul class="actions">
  <li><%= link_to "New Topic", new_project_discussion_topic_path(@project, @discussion) %></li>
  </ul>
  <h2>Discussions <%= link_to "New category", new_project_discussion_path(@project) %></h2>
  <ul>
  <li><%= link_to_unless_current "All", project_discussions_path(@project) %></li>
  <% @project.discussions.each do |discussion| %>
  <li><%= link_to_unless_current discussion.title, project_discussion_path(@project, discussion) %></li>
  <% end %>
  </ul>

  <h2>Manage</h2>
  <ul>
    <% if can? :manage, Discussion %>
      <li><%= link_to "Edit Category", edit_project_discussion_path(@project, @discussion) %></li>
    <% end %>
    <li>
    <% if @discussion.archived == 0 %>
      <%= link_to "Archive", archive_project_discussion_path(@project, @discussion), :confirm => 'Are you sure you want to archive this category?', :method => :post %>
    <% else %>
      <%= link_to "Reactivate", reactivate_project_discussion_path(@project, @discussion), :method => :post %>
    <% end %>
    </li>
  </ul>
<% end %>

<div class="topics">
  <%= render @discussion.topics %>
</div>