config/routes.rb
Taskodozer::Application.routes.draw do

  root :to => "pages#home"
  get "/about" => "pages#about", :as => "about"

  devise_for :users

  resources :projects, :except => [:destroy] do
    resources :discussions
    resources :tasks do
      get 'filter/:filter' => "tasks#index", :on => :collection, :as => "filter"
      match 'notes' => "notes#create", :on => :member, :via => :post
      match 'notes/:note_id/edit' => "notes#edit", :on => :member, :via => :get, :as => "edit_note"
      match 'notes/:note_id/' => "notes#update", :on => :member, :as => "update_note"
    end
    resources :topics do
      match 'comments' => "comments#create", :on => :member, :via => :post
      match 'comments/:comment_id/edit' => "comments#edit", :on => :member, :via => :get, :as => "edit_comment"
      match 'comments/:comment_id/' => "comments#update", :on => :member, :as => "update_comment"
    end
  end
  get "/projects/filter/:filter" => "projects#index", :as => "project_filter"
  match "/projects/:id/archive" => "projects#archive", :as => "project_archive", :via => :post
  match "/projects/:id/reactivate" => "projects#reactivate", :as => "project_reactivate", :via => :post
  match "project/:project_id/discussion/:id/archive" => "discussions#archive", :as => "archive_project_discussion", :via => :post
  match "project/:project_id/discussion/:id/reactivate" => "discussions#reactivate", :as => "reactivate_project_discussion", :via => :post

  match "project/:project_id/discussion/:id/topics/new" => "topics#new", :as => "new_project_discussion_topic", :via => :get

  resources :companies, :except => [:index, :show]

  match "/projects/:project_id/accesses/new" => "accesses#new", :via => :get, :as => "new_access"
  match "/accesses" => "accesses#create", :via => :post, :as => "accesses"
  match "/accesses/:project_id" => "accesses#create_self", :via => :post, :as => "accesses_add_self"
  match "/accesses" => "accesses#index", :via => :get, :as => "accesses"
  match "/projects/:project_id/accesses/:user_id" => "accesses#destroy", :as => "access"

  match "/topic/:topic_id/subscribe" => "subscriptions#create_topic_self", :via => :post, :as => "topic_subscriptions_add_self"
  match "/topic/:topic_id/unsubscribe/:user_id" => "subscriptions#destroy_topic", :as => "topic_subscriptions"

  get "administration/management"
  get "/manage" => "administration#home", :as => "administration_home"
  get "/manage/users" => "administration#users", :as => "administration_users"
  get "/manage/users/:id" => "administration#user_edit", :as => "administration_user_edit"
  get "/manage/companies/:id/add" => "administration#user_new", :as => "administration_user_new"
  match "manage/companies/add" => "administration#user_create", :as => "administration_user_create"
  match "/manage/users/:id" => "administration#user_update", :as => "administration_user_update"
  

end

app/controllers/administration_controller.rb
class AdministrationController < ApplicationController

  before_filter :authenticate_user!
  before_filter :check_admin
  
  def home
  end

  def users
    @companies = Company.all
  end

  def user_new
    @company = Company.find(params[:id])
    @user = User.new
    @user.company = @company
    @user.role = "client"
  end

  def user_create
    @user = User.new(params[:user])
    if @user.save
      redirect_to administration_users_path, :notice => "Successfully added user."
    else
      render :action => 'user_new'
    end
  end

  def user_edit
    @user = User.find(params[:id])
  end

  def user_update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:notice] = ("The user has been succesfully updated.")
      redirect_to administration_users_path
    else
      render :user_edit
    end
  end

private
  def check_admin
    unless current_user && current_user.admin?
      flash[:notice] = ("Only admins can do management tasks.")
      redirect_to root_path
      return false
    end
  end

end

app/helpers/administration_helper.rb
module AdministrationHelper
end

app/views/administration/home.html.erb
<% title "Management Dashboard" %>

<% content_for :sidebar do -%>
<h2>Manage</h2>
<ul>
	<li><%= link_to "People", administration_users_path %></li>
	<li><%= link_to "Projects", projects_path %></li>
</ul>
<% end -%>

app/views/administration/user_edit.html.erb
<% title "Edit user #{@user.username}" %>

<%= semantic_form_for @user, :url => administration_user_update_path(@user) do |f| %>
  <%= f.inputs do %>
  	<% unless current_user == @user && current_user.admin? %>
  	<%= f.input :role,	:as => :select, :collection => User::ROLES %>
  	<% end %>
  	<%= f.input :company %>
  <% end %>

  <%= f.buttons do %>
    <%= f.commit_button %>
  <% end %>

<% end %>

app/views/administration/user_new.html.erb
<% title "Add user" %>

<%= semantic_form_for @user, :url => administration_user_create_path do |f| %>
  <%= f.inputs do %>
  	<%= f.input :username %>
  	<%= f.input :email %>
  	<%= f.input :company %>
  	<%= f.input :role, :as => :select, :collection => User::ROLES %>
  	<%= f.input :password %>
  	<%= f.input :password_confirmation %>
  <% end %>
  <%= f.buttons do %>
    <%= f.commit_button "Add User" %>
  <% end %>
<% end %>

app/views/administration/users.html.erb
<% title "Manage People" %>

<p><%= link_to "New Company", new_company_path %></p>

<table class="users">
<% @companies.each do |company| %>
<h4><%= company.name %> (<%= link_to "Edit", edit_company_path(company) %> | <%= link_to "Add user", administration_user_new_path(company) %>)</h4>
	<% if company.users.blank? %>
		<p>No users <% if company.projects.blank? %>- <%= link_to "Delete company", company, :confirm => 'Are you sure?', :method => :delete %><% end %></p>
	<% else %>
		<table class="index">
		<thead>
			<tr>
				<th>Username</th>
				<th>Email</th>
				<th>Role</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
		<% company.users.each do |user| %>
			<tr>
				<td><%= user.username %></td>
				<td><%= user.email %></td>
				<td><%= user.role %></td>
				<td><%= link_to "Edit", administration_user_edit_path(user) %></td>
			</tr>
		<% end %>
		</tbody>
		</table>
	<% end %>
<% end %>
</table>