config/routes.rb
Taskodozer::Application.routes.draw do

  root :to => "pages#home"
  get "/about" => "pages#about", :as => "about"

  devise_for :users

  resources :projects, :except => [:destroy] do
    resources :discussions
    resources :tasks do
      get 'filter/:filter' => "tasks#index", :on => :collection, :as => "filter"
      match 'notes' => "notes#create", :on => :member, :via => :post
      match 'notes/:note_id/edit' => "notes#edit", :on => :member, :via => :get, :as => "edit_note"
      match 'notes/:note_id/' => "notes#update", :on => :member, :as => "update_note"
    end
    resources :topics do
      match 'comments' => "comments#create", :on => :member, :via => :post
      match 'comments/:comment_id/edit' => "comments#edit", :on => :member, :via => :get, :as => "edit_comment"
      match 'comments/:comment_id/' => "comments#update", :on => :member, :as => "update_comment"
    end
  end
  get "/projects/filter/:filter" => "projects#index", :as => "project_filter"
  match "/projects/:id/archive" => "projects#archive", :as => "project_archive", :via => :post
  match "/projects/:id/reactivate" => "projects#reactivate", :as => "project_reactivate", :via => :post
  match "project/:project_id/discussion/:id/archive" => "discussions#archive", :as => "archive_project_discussion", :via => :post
  match "project/:project_id/discussion/:id/reactivate" => "discussions#reactivate", :as => "reactivate_project_discussion", :via => :post

  match "project/:project_id/discussion/:id/topics/new" => "topics#new", :as => "new_project_discussion_topic", :via => :get

  resources :companies, :except => [:index, :show]

  match "/projects/:project_id/accesses/new" => "accesses#new", :via => :get, :as => "new_access"
  match "/accesses" => "accesses#create", :via => :post, :as => "accesses"
  match "/accesses/:project_id" => "accesses#create_self", :via => :post, :as => "accesses_add_self"
  match "/accesses" => "accesses#index", :via => :get, :as => "accesses"
  match "/projects/:project_id/accesses/:user_id" => "accesses#destroy", :as => "access"

  match "/topic/:topic_id/subscribe" => "subscriptions#create_topic_self", :via => :post, :as => "topic_subscriptions_add_self"
  match "/topic/:topic_id/unsubscribe/:user_id" => "subscriptions#destroy_topic", :as => "topic_subscriptions"

  get "administration/management"
  get "/manage" => "administration#home", :as => "administration_home"
  get "/manage/users" => "administration#users", :as => "administration_users"
  get "/manage/users/:id" => "administration#user_edit", :as => "administration_user_edit"
  get "/manage/companies/:id/add" => "administration#user_new", :as => "administration_user_new"
  match "manage/companies/add" => "administration#user_create", :as => "administration_user_create"
  match "/manage/users/:id" => "administration#user_update", :as => "administration_user_update"
  

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :discussion
  belongs_to :user
  has_many :subscriptions
  has_many :subscribers, :through => :subscriptions, :source => :user, :uniq => true
  has_many :comments

  attr_accessible :discussion_id, :title, :content, :subscriber_ids, :attachment, :remove_attachment
  mount_uploader :attachment, AttachmentUploader

  default_scope :order => 'created_at DESC'

  validates_presence_of :title
  validates_presence_of :content
  validates_presence_of :discussion_id

  before_save :update_attachment_attributes

  private

  def update_attachment_attributes
    unless attachment.file.blank?
      self.attachment_content_type = attachment.file.content_type
      self.attachment_file_size = attachment.file.size
      self.attachment_file_name = attachment_url.match(/[\w\s\.\-_]*$/).to_s
    end
  end
  
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  before_filter :authenticate_user!
  before_filter :init_project

  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
    @comment = Comment.new(:secret => 0)
    if current_user.client?
      @comments = @topic.comments.public
    else
      @comments = @topic.comments
    end
    @users = @topic.subscribers
    @clients = @topic.subscribers.clients
    @developers = @topic.subscribers.developers + @topic.subscribers.managers
  end

  def new
    @topic = Topic.new
    @discussions = @project.discussions 
    @subscribers = @project.users - ([] << current_user)
    if params[:id].blank?
      discussion = @discussions.first
    else
      discussion = Discussion.find(params[:id]) 
    end
    @topic.discussion = discussion
  end

  def create
    @topic = Topic.new(params[:topic])
    @topic.user = current_user
    if @topic.save
      @topic.subscribers.each do |user|
        UserMailer.new_topic_notification(user, @topic).deliver
      end
      @topic.subscribers << current_user
      @topic.save!
      redirect_to project_discussion_path(@project, @topic.discussion), :notice => "Successfully created topic."
    else
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
    if @topic.update_attributes(params[:topic])
      redirect_to project_topic_path(@project,@topic), :notice  => "Successfully updated topic."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    redirect_to project_topics_url(@project), :notice => "Successfully destroyed topic."
  end

  private

  def init_project
    @project = Project.find(params[:project_id])
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for @topic do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :discussion_id %><br />
    <%= f.text_field :discussion_id %>
  </p>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/topics/_topic.html.erb
<div class="topic">
	<h4><%= link_to topic.title, project_topic_path(topic.discussion.project, topic) %></h4>
	<p class="meta"><%= topic.user.username %> posted this in <%= link_to topic.discussion.title, project_discussion_path(topic.discussion.project, topic.discussion) %> on <%= topic.created_at.to_s(:short) %></p>
	<div class="content">
	<%= topic.content %>
	</div>
</div>

app/views/topics/edit.html.erb
<% title "Edit Topic" %>

<%= semantic_form_for @topic, :url => project_topic_path(@project, @topic), :html => { :multipart => true } do |f| %>
  <%= f.inputs do %>
    <%= f.input :discussion, :collection => @discussions, :label => "Category" %>
    <%= f.input :title, :label => "Topic title" %>
    <%= f.input :content, :label => "Description" %>
    <%= f.input :attachment, :label => "Add/Replace Attachment", :as => :file %>
    <% unless @topic.attachment.blank? %>
    <li>
      <%= link_to @topic.attachment_file_name, @topic.attachment_url %> (<%= number_to_human_size(@topic.attachment_file_size) %>)
    </li>
    <%= f.input :remove_attachment, :as => :boolean %>
    <% end %>
    <%= f.input :subscribers, :collection => @project.users, :label => "Subscribers", :as => :check_boxes %>
  <% end %>
  <%= f.buttons %>
<% end %>

app/views/topics/index.html.erb
<% title "Topics" %>

<table>
  <tr>
    <th>Discussion</th>
    <th>Title</th>
    <th>Content</th>
  </tr>
  <% for topic in @topics %>
    <tr>
      <td><%= topic.discussion_id %></td>
      <td><%= topic.title %></td>
      <td><%= topic.content %></td>
      <td><%= link_to "Show", project_topic_path(@project,topic) %></td>
      <td><%= link_to "Edit", edit_project_topic_path(@project,topic) %></td>
      <td><%= link_to "Destroy", project_topic_path(@project,topic), :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Topic", new_project_topic_path(@project) %></p>

app/views/topics/new.html.erb
<% title "New Topic" %>

<%= semantic_form_for @topic, :url => project_topics_path(@project), :html => { :multipart => true } do |f| %>
  <%= f.inputs do %>
    <%= f.input :discussion, :collection => @project.discussions, :label => "Category" %>
    <%= f.input :title, :label => "Topic title" %>
    <%= f.input :content, :label => "Description" %>
    <%= f.input :attachment, :as => :file %> 
    <%= f.input :subscribers, :collection => @subscribers, :label => "Subscribers", :as => :check_boxes %>
  <% end %>
  <%= f.buttons %>
<% end %>

<p><%= link_to "Back to List", project_topics_path(@project) %></p>

app/views/topics/show.html.erb
<% title @topic.title %>

<% content_for :sidebar do %>
  <h2>Subscribers</h2>
  <p>Stake holders: 
  <% @clients.each do |user| %>
    <span class="user">
      <%= user.username %>
      <% if admin? || user == current_user %>
        (<%= link_to "x", topic_subscriptions_path(@topic, user), :title => "Remove from project", :confirm => 'Are you sure you want to remove user from the subscribers list?', :method => :delete %>)
      <% end %>
    </span>
  <% end %>
<br />Developers: 
  <% @developers.each do |user| %>
    <span class="user">
      <%= user.username %> 
      <% if admin? || user == current_user %>
        (<%= link_to "x", topic_subscriptions_path(@topic, user), :title => "Unsubscribe from notifications", :confirm => 'Are you sure you want to remove user from the subscribers list?', :method => :delete %>)
      <% end %>
    </span>
  <% end %>
</p>
  <ul>
    <% unless @users.include?(current_user) %>
      <li><%= link_to "Subscribe", topic_subscriptions_add_self_path(@topic), :method => :post %></li>
    <% end %>
  </ul>
  <h2>Manage</h2>
  <ul>
    <% if (can? :manage, Topic) || (@topic.user == current_user) %>
      <li><%= link_to "Edit Topic", edit_project_topic_path(@project,@topic) %></li>
    <% end %>
  </ul>
<% end %>

<div class="meta">
  <div class="author"><%= @topic.user.username %> posted this in <%= link_to @topic.discussion.title, project_discussion_path(@topic.discussion.project, @topic.discussion) %></div>
  <div class="date"><%= @topic.created_at.to_s(:short) %></div>
</div>
<div class="content">
  <%= @topic.content %>
</div>
<% unless @topic.attachment.blank? %>
<div class="attachments">
  <%= render :partial => "shared/attachment", :locals => { :mymodel => @topic } %>
</div>
<% end %>

<h4>Comments</h4>

<%= render @comments %>

<div class="comments_new">
  <%= semantic_form_for @comment, :url => comments_project_topic_path(@project, @topic), :html => { :multipart => true } do |f| %>
    <%= f.inputs do %>
      <%= f.input :content, :label => "Leave a comment&hellip;", :input_html => { :class => 'autogrow', :rows => 6  } %>
      <%= f.input :attachment, :label => "Attach a file", :as => :file %>
      <% if can? :secret, Comment %>
        <%= f.input :secret, :label => "Make comment secret", :hint => "(visible only to the internal developers)", :as => :boolean, :default => "0" %>
      <% end %>
    <% end %>
    <%= f.buttons %>
  <% end %>
</div> <!-- comments_new -->