config/routes.rb
Taskodozer::Application.routes.draw do

  root :to => "pages#home"
  get "/about" => "pages#about", :as => "about"

  devise_for :users

  resources :projects, :except => [:destroy] do
    resources :discussions
    resources :tasks do
      get 'filter/:filter' => "tasks#index", :on => :collection, :as => "filter"
      match 'notes' => "notes#create", :on => :member, :via => :post
      match 'notes/:note_id/edit' => "notes#edit", :on => :member, :via => :get, :as => "edit_note"
      match 'notes/:note_id/' => "notes#update", :on => :member, :as => "update_note"
    end
    resources :topics do
      match 'comments' => "comments#create", :on => :member, :via => :post
      match 'comments/:comment_id/edit' => "comments#edit", :on => :member, :via => :get, :as => "edit_comment"
      match 'comments/:comment_id/' => "comments#update", :on => :member, :as => "update_comment"
    end
  end
  get "/projects/filter/:filter" => "projects#index", :as => "project_filter"
  match "/projects/:id/archive" => "projects#archive", :as => "project_archive", :via => :post
  match "/projects/:id/reactivate" => "projects#reactivate", :as => "project_reactivate", :via => :post
  match "project/:project_id/discussion/:id/archive" => "discussions#archive", :as => "archive_project_discussion", :via => :post
  match "project/:project_id/discussion/:id/reactivate" => "discussions#reactivate", :as => "reactivate_project_discussion", :via => :post

  match "project/:project_id/discussion/:id/topics/new" => "topics#new", :as => "new_project_discussion_topic", :via => :get

  resources :companies, :except => [:index, :show]

  match "/projects/:project_id/accesses/new" => "accesses#new", :via => :get, :as => "new_access"
  match "/accesses" => "accesses#create", :via => :post, :as => "accesses"
  match "/accesses/:project_id" => "accesses#create_self", :via => :post, :as => "accesses_add_self"
  match "/accesses" => "accesses#index", :via => :get, :as => "accesses"
  match "/projects/:project_id/accesses/:user_id" => "accesses#destroy", :as => "access"

  match "/topic/:topic_id/subscribe" => "subscriptions#create_topic_self", :via => :post, :as => "topic_subscriptions_add_self"
  match "/topic/:topic_id/unsubscribe/:user_id" => "subscriptions#destroy_topic", :as => "topic_subscriptions"

  get "administration/management"
  get "/manage" => "administration#home", :as => "administration_home"
  get "/manage/users" => "administration#users", :as => "administration_users"
  get "/manage/users/:id" => "administration#user_edit", :as => "administration_user_edit"
  get "/manage/companies/:id/add" => "administration#user_new", :as => "administration_user_new"
  match "manage/companies/add" => "administration#user_create", :as => "administration_user_create"
  match "/manage/users/:id" => "administration#user_update", :as => "administration_user_update"
  

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :company
  has_many :accesses
  has_many :users, :through => :accesses, :uniq => true
  has_many :discussions
  has_many :topics, :through => :discussions
  has_many :tasks
  
  attr_accessible :name, :slug, :description, :company_id, :status, :repository

  validates_presence_of :name, :company
  validates_uniqueness_of :name, :slug

  default_scope :order => 'created_at DESC'

  scope :active, :conditions => { :archived => 0 }
  scope :archived, :conditions => { :archived => 1 }
  scope :inquiry, :conditions => { :status => "inquiry" }
  scope :upcoming, :conditions => { :status => "upcoming" }
  scope :current, :conditions => { :status => "current" }
  scope :on_hold, :conditions => { :status => "on_hold" }
  scope :review, :conditions => { :status => "review" }

  before_validation :setup_project
  after_save :setup_discussions

  STATUSES = %w[inquiry upcoming current on_hold review]

  def to_slug(ret)
    #strip the string and make it lowercase
    ret = ret.strip.downcase

    #blow away apostrophes
    ret.gsub! /['`]/,""

    # @ --> at, and & --> and
    ret.gsub! /\s*@\s*/, " at "
    ret.gsub! /\s*&\s*/, " and "

    #replace all non alphanumeric, underscore or periods with underscore
     ret.gsub! /\s*[^A-Za-z0-9\.\-]\s*/, '_'  

     #convert double underscores to single
     ret.gsub! /_+/,"_"

     #strip off leading/trailing underscore
     ret.gsub! /\A[_\.]+|[_\.]+\z/,""

     ret
  end

  private

  def setup_project
  	if self.slug.blank?
  	  self.slug = self.to_slug(self.name)
  	end
  end

  def setup_discussions
    self.discussions.create(:title => "General")
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :authenticate_user!
  before_filter :check_admin, :only => [:edit, :update]
  before_filter :check_access, :only => [:show]

  def archive
    @project = Project.find(params[:id])
    @project.archived = 1
    @project.save
    redirect_to projects_url, :notice => "Successfully archived project."
  end

  def reactivate
    @project = Project.find(params[:id])
    @project.archived = 0
    @project.save
    redirect_to projects_url, :notice => "Successfully reactivated project."
  end

  def index
    @filter = params[:filter]
    if current_user.client?
      @projects_nb_all      = current_user.company.projects.all.count
      @projects_nb_archived = current_user.company.projects.archived.count
      @projects_nb_inquiry  = current_user.company.projects.active.inquiry.count
      @projects_nb_upcoming = current_user.company.projects.active.upcoming.count
      @projects_nb_current  = current_user.company.projects.active.current.count
      @projects_nb_on_hold  = current_user.company.projects.active.on_hold.count
      @projects_nb_review   = current_user.company.projects.active.review.count
      @projects_nb_active   = current_user.company.projects.active.count
      @projects = case @filter
        when "all" then current_user.company.projects.all
        when "archived" then current_user.company.projects.archived
        when "inquiry" then current_user.company.projects.active.inquiry
        when "upcoming" then current_user.company.projects.active.upcoming
        when "current" then current_user.company.projects.active.current
        when "on_hold" then current_user.company.projects.active.on_hold
        when "review" then current_user.company.projects.active.review
      else current_user.company.projects.active
      end
    else
      @projects_nb_all      = Project.all.count
      @projects_nb_archived = Project.archived.count
      @projects_nb_inquiry  = Project.active.inquiry.count
      @projects_nb_upcoming = Project.active.upcoming.count
      @projects_nb_current  = Project.active.current.count
      @projects_nb_on_hold  = Project.active.on_hold.count
      @projects_nb_review   = Project.active.review.count
      @projects_nb_active   = current_user.projects.active.count
      @projects = case @filter
        when "all" then Project.all
        when "archived" then Project.archived
        when "inquiry" then Project.active.inquiry
        when "upcoming" then Project.active.upcoming
        when "current" then Project.active.current
        when "on_hold" then Project.active.on_hold
        when "review" then Project.active.review
        else current_user.projects.active
      end
    end

      @companies = Array.new
      @projects.each do |project|
        @companies << project.company
      end
      @companies.uniq!
  end

  def show
    @project = Project.find(params[:id])
    @users = @project.users
    @clients = @users.clients
    @developers = @users.developers + @users.managers
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
      unless @project.repository == 0
        result = `./svncreator.sh #{@project.slug}`
        @project.repository = "svn://svn@svn.adesigns.eu/#{@project.slug}"
        @project.save
      end
      redirect_to @project, :notice => "Successfully created project."
    else
      render :action => 'new'
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      redirect_to @project, :notice  => "Successfully updated project."
    else
      render :action => 'edit'
    end
  end

private
  def check_admin
    unless current_user.admin?
      flash[:notice] = ("You don't have permission to manage projects.")
      redirect_to root_path
      return false
    end
  end

  def check_access
    unless current_user.admin? || current_user.developer? || current_user.company == Project.find(params[:id]).company
      redirect_to projects_path, :notice  => "You don't have access to that project space."
    end
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= semantic_form_for @project do |f| %>
  <%= f.inputs do %>
    <%= f.input :name, :label => "Project Name" %>
    <%= f.input :slug %>
    <%= f.input :status, :as => :select, :collection => Project::STATUSES %>
    <%= f.input :company %>
    <% if @project.new_record? %>
      <%= f.input :repository, :as => :boolean, :label => "Create repository" %>
    <% end %>
    <%= f.input :description %>
  <% end %>
  <%= f.buttons do %>
    <%= f.commit_button %>
  <% end %>
<% end %>

app/views/projects/edit.html.erb
<% title "Edit Project" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @project %> |
  <%= link_to "View All", projects_path %>
</p>

app/views/projects/index.html.erb
<% if @filter.blank?
     title "My active projects"
   else
     title "Projects / #{@filter}" 
   end %>

<% content_for :sidebar do %>
  <h2>Filter Projects</h2>
  
  <ul>
    <% if @projects_nb_active > 0 %><li><%= link_to_unless_current "My Active Projects", projects_path %> (<%= @projects_nb_active %>)</li><% end %>
    <% if @projects_nb_all > 0 %><li><%= link_to_unless_current "All", project_filter_path("all") %> (<%= @projects_nb_all %>)</li><% end %>
    <% if @projects_nb_inquiry > 0 %><li><%= link_to_unless_current "Inquiry", project_filter_path("inquiry") %> (<%= @projects_nb_inquiry %>)</li><% end %>
    <% if @projects_nb_upcoming > 0 %><li><%= link_to_unless_current "Upcoming", project_filter_path("upcoming") %> (<%= @projects_nb_upcoming %>)</li><% end %>
    <% if @projects_nb_current > 0 %><li><%= link_to_unless_current "Current", project_filter_path("current") %> (<%= @projects_nb_current %>)</li><% end %>
    <% if @projects_nb_on_hold > 0 %><li><%= link_to_unless_current "On Hold", project_filter_path("on_hold") %> (<%= @projects_nb_on_hold %>)</li><% end %>
    <% if @projects_nb_review > 0 %><li><%= link_to_unless_current "In Review", project_filter_path("review") %> (<%= @projects_nb_review %>)</li><% end %>
    <% if @projects_nb_archived > 0 %><li><%= link_to_unless_current "Archived", project_filter_path("archived") %> (<%= @projects_nb_archived %>)</li><% end %>
  </ul>

<% end %>

<% @companies.each do |company| %>
  <h4><%= company.name %></h4>
  <table class="index">
    <thead>
      <tr>
        <th>Name</th>
        <th>Status</th>
        <th>Started</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
    <% for project in company.projects & @projects do %>
      <tr class="<%= project.status %>">
        <td><%= link_to project.name, project %></td>
        <td><%= project.status.capitalize %></td>
        <td><%= project.created_at.to_s(:short_date) %></td>
        <td>
          <% if can? :manage, Project %>
            <%= link_to "Edit", edit_project_path(project) %>
          <% end %>
          <% if project.archived == 0 %>
            <%= link_to "Archive", project_archive_path(project), :confirm => 'Are you sure you want to archive the project?', :method => :post %>
          <% else %>
            <%= link_to "Reactivate", project_reactivate_path(project), :method => :post %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
    </table>
<% end %>

<% if can? :create, Project %>
<p><%= link_to "New Project", new_project_path %></p>
<% end %>

app/views/projects/new.html.erb
<% title "New Project" %>

<%= render 'form' %>

<p><%= link_to "Back to List", projects_path %></p>

app/views/projects/show.html.erb
<% title @project.company.name + ": " + @project.name %>

<% content_for :sidebar do -%>
<h2>Discussions <%= link_to "New category", new_project_discussion_path(@project) %></h2>
<ul>
<li><%= link_to_unless_current "All", project_discussions_path(@project) %></li>
<% @project.discussions.each do |discussion| %>
<li><%= link_to_unless_current discussion.title, project_discussion_path(@project, discussion) %></li>
<% end %>
</ul>

<h2>People
  <% if can? :create, Access %> 
    <%= link_to "Add people", new_access_path(@project) %>
  <% end %>
</h2>
<p>Stake holders: 
  <% @clients.each do |user| %>
    <span class="user">
      <%= user.username %>
      <% if admin? || user == current_user %>
        (<%= link_to "x", access_path(@project, user), :title => "Remove from project", :confirm => 'Are you sure you want to remove #{user.username} from #{@project.name}?', :method => :delete %>)
      <% end %>
    </span>
  <% end %>
<br />Developers: 
  <% @developers.each do |user| %>
    <span class="user">
      <%= user.username %> 
      <% if admin? || user == current_user %>
        (<%= link_to "x", access_path(@project, user), :title => "Remove from project", :confirm => 'Are you sure you want to remove user from project space?', :method => :delete %>)
      <% end %>
    </span>
  <% end %>
</p>
<ul>
  <% unless @users.include?(current_user) %>
    <li><%= link_to "Get involved", accesses_add_self_path(@project), :method => :post %></li>
  <% end %>
</ul>
<h2>Manage</h2>
<ul>
  <% if can? :manage, Project %>
    <li><%= link_to "Edit Project", edit_project_path(@project) %></li>
  <% end %>
  <li>
  <% if @project.archived == 0 %>
    <%= link_to "Archive", project_archive_path(@project), :confirm => 'Are you sure you want to archive the project?', :method => :post %>
  <% else %>
    <%= link_to "Reactivate", project_reactivate_path(@project), :method => :post %>
  <% end %>
  </li>
</ul>
<% end -%>

<h4>Description</h4>
<div class="description">
<%= @project.description %>
</div>
<% unless current_user.client? or @project.repository.blank? %>
<div class="repository">
  <strong>Repository URL:</strong>
  <span><%= @project.repository %></span>
</div>
<% end %>